name: Lint and typecheck

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  lint:
    name: Lint and typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: |
          python3 -m pip install --upgrade --user pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install poetry==1.8.2

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint with ruff
        run: |
          poetry run poe lint

      - name: Typecheck with mypy
        run: |
          poetry run poe check
